name: Build Gask

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: gask
          - os: windows-latest
            output_name: gask.exe
          - os: macos-latest
            output_name: gask

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with Nuitka
      uses: Nuitka/Nuitka-Action@v1.1
      with:
        script-name: gask.py
        onefile: true
        standalone: true
        output-file: ${{ matrix.output_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gask-${{ runner.os }}
        path: build/${{ matrix.output_name }}